### ISSUE TITLE
Tag srai not working

### ISSUE THREAD

**Issue by jobindcruz** [Program-O/Program-O#209] opened 2016-12-31 08:44 UTC
This tag (srai) not working..This is a example of aiml file

say : DO YOU KNOW WHO Isaac NEWTON IS

say : DO YOU KNOW WHO Isaac IS

```xml
<?xml version = "1.0" encoding = "UTF-8"?>
<aiml version = "1.0.1" encoding = "UTF-8"?>
   <category>
     `<pattern> WHO IS ALBERT EINSTEIN </pattern>
     `<template>Albert Einstein was a German physicist.</template>
   </category>
   
   <category>
     `<pattern> WHO IS Isaac NEWTON </pattern>
     <template>Isaac Newton was a English physicist and mathematician.</template>
   </category>
   
   <category>
      <pattern>DO YOU KNOW WHO * IS</pattern>
      <template>
        <srai>WHO IS <star/></srai>
      </template>
   </category>
</aiml>
```

**Comment by AlekzNet** [comment] 2016-12-31 15:40
Related to https://github.com/Program-O/Program-O/issues/206

**Comment by AlekzNet** [comment] 2017-01-22 23:18
Closed as a duplicate of https://github.com/Program-O/Program-O/issues/206

**Closed by AlekzNet** 2017-01-22 23:18 UTC
