### ISSUE TITLE
No response from Bot

### ISSUE THREAD

**Issue by jonnyboy** [Program-O/Program-O#122] opened 2016-04-19 21:45 UTC
I updated today and found many responses to be empty. I figured my changes may have broke something.

So, I deleted my installation and reinstalled following these guides: 
https://github.com/Program-O/Program-O/blob/master/fresh_install_README.txt
https://github.com/Program-O/Program-O/wiki/Installation-Guide

I added only 1 AIML file from https://github.com/fastcoding/aiml-en-us-foundation-alice.v1-6, salutations.aiml.

The url for the bot is https://bot.lostnfound.xyz/gui/jquery/ and gets no response. Whereas this bot here is working http://www.javier.fullcustommusic.com/gui/jquery/. 

Where can I look for error?

I have tried to import AIML sql files from https://github.com/Program-O/Program-O_SQL_Import_files but I get an error "ERROR 1136 (21S01) at line 10: Column count doesn't match value count at row 1" meaning the aiml table is missing a column that is in the aiml.sql file. I can add a column, but I can not find the correct name for it.

Thank you

**Comment by jonnyboy** [comment] 2016-04-19 22:09
I did find this in the error log.

[19-Apr-2016 18:04:54 America/New_York] PHP Notice:  Undefined variable: session_lifetime in /var/www/obot/chatbot/debug/index.php on line 28

Line 28 is: session_set_cookie_params($session_lifetime, $session_cookie_path);

**Comment by Dave-Morton** [comment] 2016-04-19 22:11
You should start by looking in the logs folder for the error logs. I tried, but got "not found" errors. I got the same thing when trying to look at the debug file that would normally be created after a conversation volley. Beyond that, look at the server's error logs, as well.

**Comment by Dave-Morton** [comment] 2016-04-19 22:13
That's an error from when I tried to access the debug file, I'll bet. It's not related to your issue, though, so I wouldn't worry about that one.

**Comment by jonnyboy** [comment] 2016-04-19 22:22
This works https://bot.lostnfound.xyz/chatbot/conversation_start.php?say=hello

**Comment by Dave-Morton** [comment] 2016-04-20 00:16
In the admin, under the top link of the nav to the left, is the configuration for your chatbot. Try changing the GUI to HTML instead of jquery and see if you can get a response from the chatbot. Also, while in there, change the debugging options to saving to file and showing everything. these can be changed back after we find out what the problem is.

**Comment by jonnyboy** [comment] 2016-04-20 05:32
I changed Response Format from json to html. The "Test Your Bot" link works, a little. But, https://bot.lostnfound.xyz/chatbot/conversation_start.php?say=hello still has no response.

Logging was already set as you asked.

After importing the aiml.sql file, I tested the bot.
No log entries are generated from the gui/jquery/ page. From the "Test your Bot" page.
`Seeker: HELLO
Carla: Yes or No?
Seeker: HOW ARE YOU
Carla: 
Seeker: ARE YOU HERE
Carla: 
Seeker: CAN YOU HELP ME
Carla:`

Where else can I look? What else can I try?

**Comment by Program-O** [comment] 2016-04-20 06:40
that yes or no error was the error that we had last weekend
before we did the that release
when the bot got stuck in bad answer mode.
are we sure that the THAT release wasnt overwirtten?

**Comment by Dave-Morton** [comment] 2016-04-20 06:45
I'll take a look, but I don't think so.

**Comment by Dave-Morton** [comment] 2016-04-20 15:43
I think that the latest fix that I pushed to deal with issue #118 may also have taken care of this one, too. Try downloading the latest from the DEV branch and see if that takes care of the problem.

**Comment by jonnyboy** [comment] 2016-04-20 19:27
I just updated to the latest dev and I am not seeing any difference in the responses.

from error.log
```
04/20/2016 15:22:18 - PHP ERROR [Notice] -Array to string conversion in /var/www/obot/chatbot/core/aiml/parse_aiml_as_XML.php on Line 118
04/20/2016 15:22:18 - PHP ERROR [Notice] -Array to string conversion in /var/www/obot/chatbot/core/aiml/parse_aiml_as_XML.php on Line 118
04/20/2016 15:22:18 - PHP ERROR [Notice] -Undefined offset: 0 in /var/www/obot/chatbot/core/aiml/parse_aiml_as_XML.php on Line 698
```

I tested both json, html and
```
https://bot.lostnfound.xyz/gui/jquery/?bot_id=1
https://bot.lostnfound.xyz/chatbot/conversation_start.php?bot_id=1&say=hello&convo_id=99&format=json&name=jonnyboy
```

Thank you for digging into this.

**Comment by FatBuck** [comment] 2016-04-29 19:18
I have a similar issue with no response, but I'm not finding the logs.  I tried to set the output from JSON to HTML, but it had no effect.  I also noticed non of the php scripts were set with execute flag, so I added the execute flag as a test, but no change.  The test results are:

{"convo_id":"eh0bfqas3b9rmd1pcolnldkcs1","usersay":"HELLO","botsay":""}

**Comment by FullCustom** [comment] 2016-05-03 22:41
Javier has a lot more than one aiml file, more than ten. Is your SQL data base setup? That was the most confusing part for me.

**Comment by Dave-Morton** [comment] 2016-05-09 17:25
@FatBuck All logs generated by Program O are in the logs folder. If you navigate to that same folder, there's a log file viewer that makes it fairly easy to read the files. You'll need to log in as admin to use the viewer, but that's about it. Let me know if you find anything.

**Comment by Dave-Morton** [comment] 2016-05-20 17:29
@jonnyboy  & @FatBuck - I ***think*** I may have found a cause for this issue and corrected it, but I'm not 100% sure. Could you both grab the latest from the DEV branch and give it a try, to see if what I found corrects the issue? Thanks.

**Comment by Dave-Morton** [comment] 2016-06-23 13:07
Since it's been more than a month without anything new being added, I'm assuming that this issue is resolved? If it hasn't, then please reopen the issue and add any additional information that you may have. Till then, I'm closing this issue.

**Closed by Dave-Morton** 2016-06-23 13:07 UTC
