### ISSUE TITLE
Not working on localhost

### ISSUE THREAD

**Issue by Straafe** [Program-O/Program-O#336] opened 2017-11-10 12:10 UTC
Installed it locally to try it out (have it at localhost/chatbot/), installation worked fine, database set up fine, added AIML files fine, but then after uploading the salutations file and trying to type "hello" I get **"Something went wrong! Error = "** 

At the bottom it has this confirmation message as well:

**The URL for the API is currently set as:
C:/inetpub/wwwroot/chatbot/chatbot/conversation_start.php.
Test this to make sure it is correct by clicking here. Then remove this message from gui/jquery/index.php And don't forget to upload your AIML files in the admin area otherwise you will not get a response!**

I don't know where it detected that file path, but I think that might be the issue. Instead of "C:/inetpub/wwwroot/chatbot/" I think it needs to be "localhost/chatbot" but I can't find out where to change it... Any ideas?

**Comment by Straafe** [comment] 2017-11-10 12:13
If I change the suggested test address to 

"http://localhost/chatbot/chatbot/conversation_start.php?say=hello"

I even get a response that looks correct (pasted below). Where can I configure it to use localhost instead of a file path? 

{"convo_id":"39r49te8rd6tbj8lvan5s8pgem","usersay":"hello","botsay":"No AIML category found. This is a Default Response.","data":{"convo_id":"39r49te8rd6tbj8lvan5s8pgem","bot_name":"trustworthybot","bot_id":1,"format":"json","unknown_user":"Seeker","user_id":"2","totallines":1,"user_name":"Seeker","conversation_lines":"1","remember_up_to":"10","debugemail":"colejben@gmail.com","debug_level":"4","debugmode":1,"save_state":"database","default_aiml_pattern":"RANDOM PICKUP LINE","bot_parent_id":"1","rawSay":"hello","data":{"id":"98","bot_id":"1","pattern":"HELLO","thatpattern":"","topic":"","template":"<random><li><srai>HI<\/srai><\/li><li>Hi there!<\/li><\/random>","score":260,"current_that":"","aiml_id":"98","track_score":"current bot, no thatpattern to match, direct pattern match, direct word match: hello"}}}

**Comment by Straafe** [comment] 2017-11-10 12:24
Also, the example bot seems to understand and respond to almost anything. Are there more AIML files available than the ones listed in the get started guide?

**Comment by Dave-Morton** [comment] 2017-11-10 14:30
Have a look in the index.php file for the given GUI that you want to use (HTML, XML or JSON). there is a great deal of internal documentation in those files that explains just what you're looking for. The code that automatically sets the URL for the interface _should_ work as intended, but sometimes fails under IIS/windows, for some strange reason. If you simply assign the variable manually to the value you already found to work, you should be just fine there.

As far as AIML goes, this is something that we have left up to the botmaster from the beginning, and that's not about to change any time soon. That said, however, here are some links that can help you to locate some AIML sets to get you started:

- http://www.alicebot.org/downloads/sets.html
- https://www.quora.com/Where-can-I-get-free-AIML-files-for-my-chatbot
- https://code.google.com/p/aiml-en-us-foundation-alice/
- http://www.square-bear.co.uk/aiml/

I hope that helps. :)

**Comment by Straafe** [comment] 2017-11-10 22:31
Thanks, trying that out. I am indeed using IIS on Windows Server 2016

**Comment by Dave-Morton** [comment] 2017-11-11 00:04
Thought so. :) Please let me know how it turns out.

**Comment by Dave-Morton** [comment] 2018-02-10 18:23
No word back for 3 months, so I have to assume everything is working. Closing this issue.

**Closed by Dave-Morton** 2018-02-10 18:23 UTC
