### ISSUE TITLE
Blank conversation page

### ISSUE THREAD

**Issue by jamieduk** [Program-O/Program-O#292] opened 2017-06-25 15:06 UTC
Blank conversation page

Made a new setup / install done all things how it said, uploaded aim file and it said to goto conversation_start page and when i did it just shows blank page!

im on mint 18 kde!

plz help me.

**Comment by patrickschur** [comment] 2017-06-25 15:17
Do you use the dev or master branch? Because the dev branch is currently a little bit buggy. We are working on that. I could reproduce the error. Thanks for you help.

**Comment by Dave-Morton** [comment] 2017-07-04 18:59
If you go to conversation_start.php without the proper GET/POST variables also sent you're _supposed_ to get a blank page. This is normal and completely expected behavior. the file conversation_start.php is nothing more than a gateway into the script, and it expects variables to be passed in order to generate an output.

**Comment by Program-O** [comment] 2017-07-05 22:02
closing as not an error 
for anyone else that is readying this....
if you want to see the bot in action navigate to /gui/plain in the url 
and do not hit the api endpoint directly!

**Closed by Program-O** 2017-07-05 22:02 UTC
