### ISSUE TITLE
Search edit AIML not including punct or tags

### ISSUE THREAD

**Issue by OverlanAI** [Program-O/Program-O#369] opened 2018-02-23 15:52 UTC
When i search for things like "My <get"  or words like "That's", it ignores everything but "My" and "That" in the returned search so i end up having to look thru many many lines when i am trying to narrow it down.

I do not know if that's a bug or WAI.
It is rather annoying whatever the case is.

tnx

**Comment by Dave-Morton** [comment] 2018-02-24 00:34
I'm not seeing what you are, for some reason. Can you please provide the following information?

1. Server OS/software & version
2. PHP version
3. Program O version and branch (`MASTER` or `DEV` - or any other that you're using, for that matter.)
4. Either text snippets from the admin page, showing what you're seeing, or
5. A screenshot of the problem, and
6. The AIML category that seems to be exhibiting the problem

Once I can see these I can understand the problem better, which will help me to be able to help you.

**Comment by OverlanAI** [comment] 2018-02-24 15:57
Win10 64bit pro (current)
Wamp Version 3.1.0 - 64bit
Apache Version: 2.4.27
PHP Version: 5.6.31
Loaded Extensions : apache2handler bcmath bz2 calendar com_dotnet Core ctype curl date dom ereg fileinfo filter ftp gd gettext gmp hash iconv imap intl json ldap libxml mbstring mcrypt mhash MySQL mysqli mysqlnd odbc openssl pcre PDO pdo_mysql pdo_sqlite Phar Reflection session SimpleXML SPL standard tokenizer wddx xdebug xml xmlreader xmlwriter Zend OPcache zip zlib.
MySQL Version: 5.7.19
Program-O-dev 2.8.9 (current)
Using the admin page of program-O with chrome (current) or MS edge with current java.

When searching for existing words in the TEMPLATE tab like 'That's" and I know full well the words are in the DB as seen in the actual DB with phpMyAdmin(current), I will see it return 0 found so I have to search for the word 'That' but now I may end up with 989 found.
Other punct. words also have the same result.
I also will see the punct. words in the results when doing other searches.
As far as 8x10 glossy photos with circles and arrows goes, I am having a problem grabbing the screenshots that are useable.
No big deal if you are not seeing it, I can use my own php script to edit with if I need to.
tnx

**Comment by Dave-Morton** [comment] 2018-02-24 17:07
Ah. So the problem is with searching in DataTables (the JavaScript package that creates the tables on the page) using punctuation causes a fail. That makes sense. I'll give that a try and see what's going on.

**Comment by OverlanAI** [comment] 2018-02-24 19:11
Yah that sounds about right. I tend to stomp on the gas more than the break, so sometimes my reports can be a bit confusing.
sry about that.

**Comment by Dave-Morton** [comment] 2018-02-25 00:06
I've found the problem, and a fix for it will be in the next `DEV` release. It seems that the dataTables JS code changes certain characters into HTML entities prior to sending them to the PHP back-end script. I should have the fix pushed to GitHub here by the end of the weekend.

**Comment by OverlanAI** [comment] 2018-02-25 15:10
No rush man, it is not a show stopper, just annoying LOL

**Comment by Dave-Morton** [comment] 2018-02-25 20:58
It may take me a bit longer to publish the next update. It seems that some of the _other_ code refactoring has introduced some rather persistent bugs that need to be dealt with before I can push the code. But I'll get it done, and soon.

**Comment by Dave-Morton** [comment] 2018-02-26 22:31
Ok, I've got good news and not so good news. I've found the issue for about 95% of this, and have fixed that 95%. the only character that I cannot get to seem to behave is the left angle bracket (<), which is defying me. This character is, of course, the beginning of an XML/HTML/AIML tag, so is being handled differently within the `dataTables` JS code, and since that code is called from a CDN, altering it isn't possible in Program O's current configuration. That said, however, I DID download datables.js from the CDN and plugged it into Program O for testing, and the issue still eludes me for now. I'm not giving up on this, but I AM putting it on the back burner for now. I'll be pushing the "95% fix" shortly, after I finish my testing, and providing that no new bugs have cropped up.

**Comment by OverlanAI** [comment] 2018-02-27 16:31
Good job man
That < may be one you can have it replace with a NULL when searching because the result will no doubt get so many hits anyway it would defeat the point.
I have to think about that more and I may be wrong about it.
If you put in whole TAG like <TAG/> it should still be just as good, as It is actually looking for nullTAG/>.
But i have not had my coffee yet lol.
Anyway it sounds ok to me and may be fine if it ignores < anyway.
TNX

**Comment by OverlanAI** [comment] 2018-03-04 19:34
A lot better than is was, at least i can narrow things down a lot better now, and you already know about the < so until you go back to that problem again, we can close this report, and open a new one later that is less general.
tnx

**Closed** 2018-03-05 15:23 UTC
Labels: review
