### ISSUE TITLE
Missing slash - pox.dkchat/chatbot/conversation_start.php

### ISSUE THREAD

**Issue by kengberg** [Program-O/Program-O#275] opened 2017-05-15 21:19 UTC
Hi

I'm missing a slash, when I go to:
http://pox.dk/chat/gui/jquery/index.php

It says that my "URL for the API is" pox.dkchat/chatbot/conversation_start.php - that doesn't seem right..

I've tried fixing it, but to no avail.
Also When I test the bot from the admin interface - it works - but when I try it through "Talk to bot" - it doesn't do anything at all..

Regards
     Kasper

**Comment by Dave-Morton** [comment] 2017-05-15 23:42
Hello, Kasper.

this is odd, because I just tested this on not only my local development server (A windows 10 machine with Apache) and my remote server (a RHEL box, also with Apache), and they both have the forward slash that is missing from your page. Since I've tried the link you've provided and see plainly that the slash is, indeed, missing I have no clue as to why this is so. So let's start at the beginning, and see about finding out a few things. Please read [this wiki page](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) to find out the sort of information that we'll need to get to the bottom of this issue. Once I have that information I can see about using one of my virtual machines (or create a new one if necessary) to track the problem down. Thanks.

**Comment by kengberg** [comment] 2017-05-16 15:07
Alright I have some extra infor for you here and a debug file:

OS:	Debian Linux 8.0
Webserver:	Apache 2
PHP: 5.6
PHP safe-mode: Off
MySQL:	MySQL 5.6

[bde1486d6212898e9351d4f7b9e40251.txt](https://github.com/Program-O/Program-O/files/1004915/bde1486d6212898e9351d4f7b9e40251.txt)

Please let me know if you need more - and thanx in advance for taking a look!

Kasper

**Comment by Dave-Morton** [comment] 2017-05-16 16:46
I've got a Debian 7/Apache setup, but not Debian 8. I'll have to create a new VM with those specs, but I can't do that for a couple of days, as I have finals today and tomorrow. but I promise I'll get to it. :)

**Comment by kengberg** [comment] 2017-05-16 18:48
Awesome - looking forward to it..

**Comment by Dave-Morton** [comment] 2017-05-24 06:36
I haven't forgotten about this, @kengberg - I've just been unable to get a working Debian 8 VM working yet. I think I'm going to have to either update or uninstall/reinstall my VM software, and that's just a bit time consuming. Still, I'll do what I can.

**Comment by kengberg** [comment] 2017-05-24 06:45
Thank you for trying!

I hope to create a virtual parent, for advising in different areas.. So I'll keep working on the AIML-files.

Regards.

**Comment by patrickschur** [comment] 2017-05-25 16:08
I tested this so far on my virtual machine with Debian 8.8 and PHP 5.6, but I couldn't reproduce such strange behaviour.

Have you tried to set the `ServerName` directive in your `/etc/apache2/sites-available/000-default.conf` file? **Important**: This file can also have a different name.

The line with `ServerName` is commented on default, when you uncomment this line and set this to your domain name this might help.

**Comment by Dave-Morton** [comment] 2017-05-25 16:20
good point, @patrickschur - I'm glad you have a working Debian 8 VM. I'm still having no luck getting mine to work.

**Comment by Program-O** [comment] 2017-07-05 22:09
closing no further input from original reporter
and @Dave-Morton bug fix has fixed this

**Closed by Program-O** 2017-07-05 22:09 UTC
