### ISSUE TITLE
API JSON

### ISSUE THREAD

**Issue by alianrkeasan** [Program-O/Program-O#324] opened 2017-08-29 20:06 UTC
Hello, I would like to access the chatterbot 2.6.5 from my OpenSimulator Virtual World and I've tried http://address/chatbotname/chatbot/conversation_start.php?say= but It is not working. I receive some errors on the screen.

What could it be? I have a 2.4.7 version that works fine.

thanks.

**Comment by patrickschur** [comment] 2017-08-30 06:57
> But it is not working.

This kind of error message is not really helpful for us... 
It would be nice if you could give us more information about the errors you receiving.

Do you know that your GET parameter `say` is empty or is this just an example?

**Comment by alianrkeasan** [comment] 2017-08-30 12:46
Hi Patrick,

I left the say empty because the bot will say something as an answer accordingly to the user's input.

I've attached the screen with the answer with error I receive.

Here it is the script that gets the answer.

listen(integer channel, string name, key id, string message)
    {
        llSetText("Esperando por resposta ...", <1.0, 1.0, 0.0>, 1.0);

        // have we started a conversation yet?  ORIGINAL ==>> JSON
        if (conversationID == "")
            conversationRequest = llHTTPRequest(programoURL
                + llEscapeURL(message)
            + "&bot_id=5&format=json"
            , [HTTP_METHOD, "GET", HTTP_MIMETYPE, "plain/text;charset=utf-8"], "");
        else // use the convo_id we have
            conversationRequest = llHTTPRequest(programoURL
                + llEscapeURL(message)
            + "&convo_id=" + conversationID
            + "&bot_id=5&format=json"
            , [HTTP_METHOD, "GET", HTTP_MIMETYPE, "plain/text;charset=utf-8"], "");

        // did we quit chatting?
        if (message == "quit" || message == "bye")
        {
            state default;
        }
    }



![capturardf](https://user-images.githubusercontent.com/8314561/29872826-8dedf236-8d67-11e7-837a-5f481a81302c.PNG)

**Comment by Dave-Morton** [comment] 2017-08-30 13:06
Translation of the initial message from Portuguese:
"At any time enter messages in the chat space that this bottom bar. The tutor Athena is prepared to answer direct questions about the subject of the laboratory" _ Google Translate

The error message is telling me that Program O could not find a match in the AIML table to correspond with the input given, so it's sending out the default error response which, in English, is "Sorry, I do not understand. Can repeat?" (again, Google Translate)

What this means is that most likely the bot isn't receiving the user's input. It's hard to say, though, because the image you've shared doesn't contain the entire data object from the looks of it.

By the way, rather than post a screenshot of the response, a simple copy/paste would be much better, since I can use the same method with Google Translate if necessary, instead of having to type what I see into a text editor.

Also, here's what a typical JSON response looks like:

```JSON
{"convo_id":"Dave","usersay":"test","botsay":"This is just a test.","data":{"convo_id":"Dave","bot_name":"fooBot","bot_id":1,"format":"json","unknown_user":"Friend","user_name":"Friend","user_id":"9","totallines":1,"conversation_lines":"1","remember_up_to":"10","debugemail":"dmorton@geekcavecreations.com","debug_level":"4","debugmode":1,"save_state":"session","default_aiml_pattern":"RANDOM PICKUP LINE","bot_parent_id":"1","rawSay":"test","data":{"id":"960","bot_id":"1","pattern":"TEST","thatpattern":"","topic":"","template":"This is just a test.","score":260,"current_that":"how are you","aiml_id":"960","track_score":"current bot, no thatpattern to match, direct pattern match, direct word match: test"}}}
```

As you can see, there is a LOT of data missing from yours, and some of that data is relevant to the issue at hand.

**Comment by Dave-Morton** [comment] 2017-08-30 13:19
A friend of mine, @tringate (AKA Slow Putzo) may be able to assist with this. Not only is he familiar with Program O and AIML (he's one of the people responsible for AIML in the first place), he's also OpenSim, and we just worked on a similar problem with his Genie SL avatars, so he might have some insight. I'll reach out to him, and see if he can help.

**Comment by tringate** [comment] 2017-08-30 21:40
Dave and all.  I suspect the issue is in opensim the http request is getting the extra data that is in the new program-o data package.  I had the same issue.  

Here is the new HTTP response routine I am using in my lsl code on opensim.

http_response(key request_id, integer status, list metadata, string body)
    {
        list lines;
        if (request_id == grequestId)
        {    // response coming from the chat server
            if (status != 200) llSay(0,"HTTP Error " + (string)status + ": " + body);
            else 
            {
                gCMDlines = [];//clear the old list
                string body1 = llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, llSubStringIndex(body, ",\"data\":")-2);//get the payload of the input line
                gCMDlines = llParseString2List(body1, ["#"], [] ); // parse into individual command lines for each command
                llSetTimerEvent(.03);// trigger timer to process command list
            }
        }
    }

This is the line of code that I needed to change.  This routine has other code in it specifically for the "genie" project and would not be needed for a standard bot.

string body1 = llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, llSubStringIndex(body, ",\"data\":")-2);//get the payload of the input line

This line gets only the text response received from program-o by eliminating everything befor and after the text.  In the new release of program-o there is new data appended to the data package that didn't exist in the old release so the original lsl code just took everything to the end of the data package.

Here is the line of lsl code this user is mostlikely presently using in their inworld script.

string body1 = llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, -3);//get the payload of the input line

I hope this is the problem that  alianrkeasan is experiencing.  I know they will need to make this modification if they don't want all the extra data printer.

**Comment by tringate** [comment] 2017-08-30 21:46
As a follow up, it isn't the sending to program-o that is the issue.  The bot receives the information with the original input code used by the older program-o system.  It's the data that is returned by program-o that has changed and the http response function is where that data arrives in opensim.  The modification to the data package "unpack" is now required for this release of program-o.

**Comment by tringate** [comment] 2017-08-30 21:56
The lsl routine that was posted is the routine that the script running inworld on opensim uses to "receive" the information typed into the users screen inworld, and then sends it to program-o.  I know it gets kind of confusing when you have to both "listen" and "send to the interface inworld, and "listen" and send to the interface going over the internet to program-o.  The http request is what SENDS the dato TO program-o, while the http response is what RECEIVES the data from program-o.

The listen function is on the in-world side, not the Internet side.

I hope that helps with the understanding of what the lsl script is doing.

**Comment by tringate** [comment] 2017-08-30 22:16
I noticed that the two lines of lsl code I posted do not display correctly here in this forum because in the lsl code the quotes are escaped for those that are in the data and all of that has been removed here in this forum.

Here are the two lines using the "code function:
`string body1 = llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, llSubStringIndex(body, ",\"data\":")-2);//get the payload of the input line`

and the old original same line:
`string body1 = llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, -3);//get the payload of the input line`

**Comment by Dave-Morton** [comment] 2017-08-30 22:28
I usually just encapsulate my code with three backtick characters (\`) in a row, both before and after the blocks of code, and I generally edit posts from others to reflect this when necessary. It makes the code a LOT easier to read.

**Comment by alianrkeasan** [comment] 2017-08-31 12:00
Hi @tringate thanks for the help. Now i'm using the following code:

http_response(key request_id, integer status, list metadata, string body)
    {
        list lines;
        if (request_id == grequestId)
        {    // response coming from the chat server
            if (status != 200) llSay(0,"HTTP Error " + (string)status + ": " + body);
            else 
            {
                gCMDlines = [];//clear the old list
                string body1 = llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, llSubStringIndex(body, ",\"data\":")-2);//get the payload of the input line
                gCMDlines = llParseString2List(body1, ["#"], [] ); // parse into individual command lines for each command
                llSetTimerEvent(.03);// trigger timer to process command list
                string botReply  = llGetSubString(body,  llSubStringIndex(body, "\"botsay\":\"") + 10, llSubStringIndex(body, ",\"data\":")-2);//get the payload of the input line
    
            }
         
                llInstantMessage(avatar, botReply);
            }
        }
    
Now I'm getting the error that "it was not possible to convert list type into string. there is a explicit conversion. need cast(77,28). errror: CS0266..."

Sorry Dave that I've send an image, that is because OpenSim does not allow me to copy the code.

And I have forget to say that the part "At any time enter messages in the chat space that this bottom bar. The tutor Athena is prepared to answer direct questions about the subject of the laboratory" was a script outside the bot.

Thanks.

**Comment by alianrkeasan** [comment] 2017-08-31 12:01
http_response(key request_id, integer status, list metadata, string body)
    {
        list lines;
        if (request_id == grequestId)
        {    // response coming from the chat server
            if (status != 200) llSay(0,"HTTP Error " + (string)status + ": " + body);
            else 
            {
                gCMDlines = [];//clear the old list
                string body1 = llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, llSubStringIndex(body, ",\"data\":")-2);//get the payload of the input line
                gCMDlines = llParseString2List(body1, ["#"], [] ); // parse into individual command lines for each command
                llSetTimerEvent(.03);// trigger timer to process command list
                string botReply  = llGetSubString(body,  llSubStringIndex(body, "\"botsay\":\"") + 10, llSubStringIndex(body, ",\"data\":")-2);//get the payload of the input line
    
            } 
         
                llInstantMessage(avatar, botReply);
            }
        }
    





pasting the code again

**Comment by alianrkeasan** [comment] 2017-08-31 12:01
>  http_response(key request_id, integer status, list metadata, string body)
    {
        list lines;
        if (request_id == grequestId)
        {    // response coming from the chat server
            if (status != 200) llSay(0,"HTTP Error " + (string)status + ": " + body);
            else 
            {
                gCMDlines = [];//clear the old list
                string body1 = llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, llSubStringIndex(body, ",\"data\":")-2);//get the payload of the input line
                gCMDlines = llParseString2List(body1, ["#"], [] ); // parse into individual command lines for each command
                llSetTimerEvent(.03);// trigger timer to process command list
                string botReply  = llGetSubString(body,  llSubStringIndex(body, "\"botsay\":\"") + 10, llSubStringIndex(body, ",\"data\":")-2);//get the payload of the input line
    
            } 
         
                llInstantMessage(avatar, botReply);
            }
        }
    

>

**Comment by alianrkeasan** [comment] 2017-08-31 12:02
Here it is my listen code 

 listen(integer channel, string name, key id, string message)
    {
        llSetText("Esperando por resposta ...", <1.0, 1.0, 0.0>, 1.0);

        // have we started a conversation yet?  ORIGINAL ==>> JSON
        if (conversationID == "")
            conversationRequest = llHTTPRequest(programoURL
                + llEscapeURL(message)
            + "&bot_id=5&format=json"
            , [HTTP_METHOD, "GET", HTTP_MIMETYPE, "plain/text;charset=utf-8"], "");
        else // use the convo_id we have
            conversationRequest = llHTTPRequest(programoURL
                + llEscapeURL(message)
            + "&convo_id=" + conversationID
            + "&bot_id=5&format=json"
            , [HTTP_METHOD, "GET", HTTP_MIMETYPE, "plain/text;charset=utf-8"], "");


        // did we quit chatting?
        if (message == "quit" || message == "bye")
        {
            state default;
        }
    }

**Comment by tringate** [comment] 2017-08-31 15:11
alianrkeasan,

You do not want to use the entire http response routing I posted.  Most of that code requires the genie code to work.

Your original http response code should have had a line that looks something like this:
`string botReply = llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, -3);//get the payload of the input line

You want to change that one line to look like this:`
`string botReply = llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, llSubStringIndex(body, ",\"data\":")-2);//get the payload of the input line`

The change you are making is changing the -3 parameter to be `llSubStringIndex(body, ",\"data\":")-2`

That addition strips off all of the new data added by the new release of program-o.

Your routine should look like this after the modification based on what you posted.

`http_response(key request_id, integer status, list metadata, string body)
{
list lines;
if (request_id == grequestId)
{ // response coming from the chat server
if (status != 200) llSay(0,"HTTP Error " + (string)status + ": " + body);
else
{
string botReply = llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, llSubStringIndex(body, ",\"data\":")-2);//get the payload of the input line

        }
            llInstantMessage(avatar, botReply);
        }
}`

**Comment by alianrkeasan** [comment] 2017-08-31 15:57
Hi tringate,

thanks again.

I've changed the code but now it looks like I'm not finding any category match in my KB, always showing me a random standard answer.

I've attached the full code I'm using.

[lslcode.txt](https://github.com/Program-O/Program-O/files/1267708/lslcode.txt)

**Comment by Dave-Morton** [comment] 2017-08-31 16:03
In addition to the LSL file, the debug file from the bot would be very helpful in determining what's going on. The file will be in Program O's chatbot/debug folder, and it will be named the same as your conversationID, but with a .txt extension.

**Comment by alianrkeasan** [comment] 2017-08-31 16:07
[3qjboaclgiakd3u195qt8b.txt](https://github.com/Program-O/Program-O/files/1267749/3qjboaclgiakd3u195qt8b.txt)

**Comment by Dave-Morton** [comment] 2017-08-31 19:34
Ok, I had a look and here is what I see from the debug file:

```
31-08-2017 15:56:24.10366[2][4] - Elapsed time: 0.000 milliseconds
[conversation_start.php][Called outside of function][198]
Details:
User say: OOOO
Convo id: 3qjboaclgiakd3u195qt8b
Bot id: 5
Format: json
-----------------------
```
This gives me the input details. The bot ID matches your SL bot, the conversation ID also matches, the output format is JSON and the input is... Well, it's "OOOO" (after normalization)

More than that, here is the SQL query:

```31-08-2017 15:56:24.11926[3][4] - Elapsed time: 0.000 milliseconds
[find_aiml.php][find_aiml_matches][1174]
Core Match AIML sql: 
SELECT `id`, `bot_id`, `pattern`, `thatpattern` , `topic`, `filename` FROM `newbot`.`aiml` WHERE
   bot_id = '5'  AND (
  `pattern` = '_' OR
  `pattern` = '*' OR
  `pattern` = 'OOOO' OR
  `pattern` = ''
   OR `thatpattern` LIKE '%*%' OR `thatpattern` LIKE '%_%'
  ) AND `topic`='' OR `topic` like '%*%' OR `topic` like '%_%' ORDER BY `topic` DESC, `pattern` ASC, `thatpattern` ASC,`id` ASC;
-----------------------
```

Again, with the input showing as "OOOO". So far so good. What did it match? Let's look:

```
31-08-2017 15:56:24.13486[2][4] - Elapsed time: 15.601 milliseconds
[find_aiml.php][find_aiml_matches][1181]
FOUND: (202) potential AIML matches
```
Everything so far looks good, but from there things went south. There are literally hundreds of lines of `building wildcards for 'pattern'` or `building wildcards for 'topic'` that should not be repeating so often, so this is something I need to look into. However, this isn't the cause of your problem. this is:

```
31-08-2017 15:56:24.18166[1][4] - Elapsed time: 0.000 milliseconds
[find_aiml.php][unset_all_bad_pattern_matches][331]
Error: FOUND NO AIML matches in DB
-----------------------
```

So for whatever reason (most likely because you don't have a fallback category in your AIML table) Program O couldn't find a matching AIML category to parse, so it displayed the "default error response". Looking back at the SQL query:

```SQL
SELECT `id`, `bot_id`, `pattern`, `thatpattern` , `topic`, `filename` FROM `newbot`.`aiml` WHERE
   bot_id = '5'  AND (
  `pattern` = '_' OR
  `pattern` = '*' OR
  `pattern` = 'OOOO' OR
  `pattern` = ''
   OR `thatpattern` LIKE '%*%' OR `thatpattern` LIKE '%_%'
  ) AND `topic`='' OR `topic` like '%*%' OR `topic` like '%_%' ORDER BY `topic` DESC, `pattern` ASC, `thatpattern` ASC,`id` ASC;
``` I notice something else strange. Where the default AIML pattern should be there is nothing. The location in the SQL query where it says `pattern = ''` should hold this default AIML pattern, and Program O has a default for this of `RANDOM PICKUP LINE`. If you don't change the value of that pattern in the bot config it should still be there, which means that it was somehow removed from the config, either manually, or via the bot config panel in the admin page.

So my suggestion to you at this point is to put something back in the bot config that matches the pattern of an AIML category for just that purpose and give it another try. You don't have to use `RANDOM PICKUP LINE`, but it should be *something*. I recommend using just a simple \* if all else fails.

**Comment by Dave-Morton** [comment] 2017-08-31 19:43
While looking into that problem I noticed in your debug that I wanted to check out, I noticed that things weren't adding up, so O looked at your debug file again and saw that you're using version 2.6.5 which is fine, but we're on a new version that's far less buggy than 2.6.5 was, so I also recommend that you upgrade versions. I think you're going to like it better. I know that @tringate does. 😀

**Comment by tringate** [comment] 2017-08-31 22:36
Looking at your "listen" routine I do not see anything wrong but you are listening to all channels because you are not checking for a specific channel.  Normally since you are chatting on open chat in opensim you would check to see if the channel was "0" zero, then execute the code you have.

I doubt that is your problem, but the listen as written will send any text it received on and channle to program-o.  Considering there are 65,000 channels on the plus channels and the same number on the negative channels there could be something that is saying "OOOO" which does look a bit odd to me.

I would recommend you place all of your code into a simple if statement like this:
`
    listen(integer channel, string name, key id, string message)
    {
        if(channel == 0)
        {
                 all your code here
        }
    }
`

**Comment by Dave-Morton** [comment] 2017-08-31 22:43
I would also like to further suggest that you test the chatbot _outside_ OpenSim, just to make sure that it's working as expected. You can do this through any of the provided GUI clients. this is also an excellent way to separate problems in that you can test the bot without being attached to LSL script. If the bot behaves outside OpenSim then you have a better idea of where to look for potential problems.

**Comment by tringate** [comment] 2017-08-31 22:53
Another thought would be to add a category statement of "OOOO" to your AIML and see if it is found.  But Dave's suggestion to use the "test your bot" or "talk to bot" will tell you if things are right without needing to run anything other than program-o.

For sure update to version 2.6.7 of program-o as well.

**Comment by alianrkeasan** [comment] 2017-09-01 22:49
My bot is working fine and my listen channel is 77 that is in line of the script:
listenChannel = llListen(77, "",  llDetectedKey(0), "");

My opensim bot is not answering anything outside this channel.

I've added a category with pattern of OOOO and it does not respond inside the virtual world (outside is working fine).

I believe program-O is not interpreting correctly what is being send from opensim, maybe something I have to change in LSL code to do this.

I'm sending messages i'm certain there is a match on KB.

Maybe it could be  HTTP_MIMETYPE, "plain/text;charset=utf-8" 

Maybe UTF-8 is not interpreted?!

On the debug it shows all the random answers exists in KB but it cannot reach to them, always show me the global_config $error_response.

**Comment by tringate** [comment] 2017-09-02 07:26
Ok, lets set some ground work first so we can spot what might be the difference and solve your issue;

My servers run Fedora release 26 at the current update level
My computer is running Windows 10 at whatever MS decides to push to it in terms of updates.
I use both the Firestorm and Singularity viewers to access opensim.

The version of opensim I am running is the latest OSgrid 0.9.1.0 (Dev)  396ab14: 2017-08-25
I run this code both on OSgrid and on a standalone.


Now for the specifics.  I have heavily modified the program-o code with new functions which have nothing to do with this problem but my code does have additional things added to the handshake between the opensim world and the program-o service.

Here is the exact code I use to send a data packet to the program-o service.

`ChatSend(string message)
{   /* send message to bot chat server */
    grequestId = llHTTPRequest(gProgramoURL + "/chatbot/conversation_start.php?say=" + llEscapeURL(message) + " NPCID " + gGenieChatID +  " " + gVersion +  " " + gAvieID + "&convo_id=" + gAvieID + "&bot_id=" + gBotID + "&format=json", [HTTP_METHOD, "GET", HTTP_MIMETYPE, "plain/text;charset=utf-8"], "");`

Here is the same code with my additions removed.

`ChatSend(string message)
{   /* send message to bot chat server */
    grequestId = llHTTPRequest(gProgramoURL + "/chatbot/conversation_start.php?say=" + llEscapeURL(message) + "&convo_id=" + gAvieID + "&bot_id=" + gBotID + "&format=json", [HTTP_METHOD, "GET", HTTP_MIMETYPE, "plain/text;charset=utf-8"], "");`

You should try to match up your code to mine and if there is any difference, make a modification.
Labels of course may be different than yours.

I will say that in the sending of data to program-o I have not had to make any changes to the code at all between the different versions.

So I can make sure I understand what you are typing on your keyboard I presume you are typing into the chat window the following:
/77 OOOO

This tells the viewer to send the message to opensim using channel 77.

What is clear to me is that opensim is sending something, and program-o is receiving something.

It is also clear to me that opensim is receiving something in return.

Do not be confused by the fact that using the non opensim tools to verify the chat is working does not mean that you are actually sending and receiving correctly.

If indeed you were expecting to send OOOO to program-o when you first asked the question, I am wondering why you needed to add the category?

It is my impression that program-o is getting something send to it that looks like OOOO and the real question is where is it coming from?

if you had a program that was working just fine with the out of the box program-o back on release 
V2.4.7 or before, then the upgrade to program-o to V2.6.7 should only require one line of code to me modified in that opensim script.

`string body1 = llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, -3);//get the payload of the input line`

It needs to be modified to remove the new added stuff that the new release has appended to the actual data packet.  It is appended immediately behind the "message" data which now is identified by the characters   ,"data":  The modification to the received data simply removes all of that added information by finding the start of that character sequence and drops it.

If you do not make this modification, what you will see returned is a bunch of very confusing data several lines long and inside you will see that your actual expected data is there along with hundreds of other characters of new data.

You do not get any errors. what you see is actually what program-o sent.  Unless you are a developer, you don't need any of this and most of it is not understandable unless you are a program-o developer.

The code line I replaced the above code line with is:
`string body1 = llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, llSubStringIndex(body, ",\"data\":")-2);//get the payload of the input line`

As you can see I am using the same functions to find the "end" of the string I want to put into the variable body1 as I did to find the starting of the actual "message".

No other code change is necessary to ignore the new added information that program-o has added.

If you are indeed running program-o V2.6.7 and the only modification you make is to add this modification to that one single line, everything should work as before.

That assumes you have loaded the identical AIML you were using before, and the same version of opensim.

The problem I have is that I do not have exactly what you have typed in the chat window of your viewer, nor do I have what was sent back as a response.

I just used Singularity viewer to chat with my genie which is a bot running in opensim.  Her is a simple exchange:
[11:44 PM]  Slow Putzo: who am i
[11:44 PM]  Heather Genie: You are Slow.

This was easily captured by doing a copy/paste from the chat window and shows exactly what I sent and what was returned.

Trying to help find the problem you are having without knowing exactly what was entered in and what was returned is making this a guessing game.

Here is the exact same thing done using the "Test your bot" tool in program-o
Seeker: who am i
bot: You are undefined.

The reason the names "Seeker" and "bot" are used is because program-o has no idea how to log into my AIML so it uses an "unknown" user of "Seeker" and the name of my bot which is called "bot".

The two exchanges are actually identical but look different because of the extensive additions I have made to program-o and to the AIML code.

Your screen shot does give this information and because of the language difference it is very hard for me to figure out what the input and output is.

I'm not sure why you can't copy/paste from you chat window and the IM window of your viewer and put the code here in a post.

Looking at your screen shot that you posted, the actual second line looks like the response from you bot and everything after the word  repetir?  is the new data that has been added in release 2.6.7

With the single one line script modification I have outlined here all that data should be removed in your response.

If the line ended at repetir? with nothing else behind it would the response been right?

If so you are making this much more difficult by adding information about what is in the logs and error messages, because there are no error messages in the screen shot you posted.  You sent a input to your bot and it answered something with a bunch of added information to what you expected.

If I could see those exact two lines, one from your working release, and one from V2.6.7 I could see if we are working on the same issue or something totally different.

In your screen shot there is no "OOOO" that I see.

A test of a simple small exchange would be much better than one that starts with a multi sentence input.

How about something simple like "hi"

I really believe you have two problems.  The one in the screen shot is displaying the one that my fix is directed at.  That is the removal of all that extra information.

The first line looks to be also from the bot, no where is there something showing what you typed in to get those responses.

How about loading a single category AIML statement into the bot and no other AIML

`<category><pattern>HI</pattern><template>
Hi back.
</template></category>`

Then say hi to your bot and post the response.
Use Clear AIML categories  in program-o to be sure you have all AIML removed.

**Comment by Dave-Morton** [comment] 2017-09-02 11:38
I think that one thing that __I__ can do to help with this is to make that additional data "optional" per bot by adding an option to turn it on/off in the bot selection screen. This will require a bit of a reconfigure of the database, though, to make a place to store the setting. I'm not sure I want to make such a drastic change for just that, however, as that would require a version change (2.7.0 anyone?).

**Comment by tringate** [comment] 2017-09-02 16:49
Dave,

Accounting for the extra data and using, or eliminating it in opensim is a very simple fix.  Because it is something that has been added, it did require a small modification to the lsl code.

The way the lsl code currently receives the data is rather a poor way to do it.  The sent data package has a specific syntax and contains different elements.  The only element of that data package that opensim is concerned with is the "botsay" element which before was the last element.

The present way it is found is to look for where it starts, and where it ends.  Unfortunately the end position is being found by looking for the "data" element start, rather than the "botsay" end.

Before it looked for where it started, and went to the end of the data package.  Now a new element has been added behind the message segment so the old way of going to the end of the data package is no longer valid.  The best way would be to know what the entire syntax is and rather than  look for the "data" element,  would be to look for a specific element, and what the termination syntax of an element is.  I suspect that may be more difficult since the "botsay" element can contain any character sequence including punctuation's.

I still think this issue is two different issues.  Why it is not receiving the correct input is still not been figured out.  Something else is going wrong.  Fixing the display of the additional information only solves what I ran into.  I did not have a problem with finding an AIML match to my inputs.

**Comment by Dave-Morton** [comment] 2017-09-02 17:06
You've made some good points, Tom. And you're also probably right in that there are two distinct and different problems going on here. Let's see if we can get the return string sorted out (which it already should be, I think), then tackle what remains. @alianrkeasan have you made any progress so far?

**Comment by tringate** [comment] 2017-09-02 23:22
Today I rewrote the HTTPRESPONSE routine to work correctly reguardless of where the "botsay" segment is placed in the response line.

`    http_response(key request_id, integer status, list metadata, string body)
    {
        list lines; // use list to parse special multi command responses
        if (request_id == grequestId)
        {    // response coming from the chat server
            if (status != 200) llSay(0,"HTTP Error " + (string)status + ": " + body);
            else 
            {
				gCMDlines = [];//clear the old list
				string botresponse = llDumpList2String(llParseStringKeepNulls(llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, -1), ["\\\""], []), "#@*$#");
				integer end = llSubStringIndex(botresponse, "\""); // find real end of botsay element pointer
				if (end != 0) 
				{
					botresponse = llGetSubString(botresponse, 0, end-1);//get the bot response
					llStringTrim(botresponse, STRING_TRIM); // remove all white space
					botresponse = llDumpList2String(llParseStringKeepNulls(botresponse, ["#@*$#"], []), "\""); // replace tag with double quote
				}
				else botresponse = ""; // response is empty
				gCMDlines = llParseString2List(botresponse, ["#"], [] ); // parse into individual command lines for each command
                llSetTimerEvent(.03);// trigger timer to process command list
            }
        }
    }`

**Comment by alianrkeasan** [comment] 2017-09-04 19:33
Hi guys, I noticed my script was with bot id incorrect :( 
Sorry about that.

Now it is answering accordingly, but I'm with ~ ç ú á é problems like:

" Eu n\u00e3o tenho certeza de que estou entendendo voc\u00ea completamente. Isto \u00e9 muito gen\u00e9rico!"

The correct would be:

"Eu não tenho certeza de que estou entendendo você completamente. Isto é muito genérico!"

Translation: 
"I'm not sure I'm understanding you completely. This is very generic!"

I also noticed that I'm getting always a new user id / conversation id, unabling the possibilite of think or that tag processing.

Here it goes my current script:

string programoURL = "http://143.54.95.244/metis/chatbot/conversation_start.php?say=";
key avatar = NULL_KEY;
string avatarName = "";
integer listenChannel = 77;
string conversationID = "";
key conversationRequest = NULL_KEY;

default
{
    state_entry()
    {
        llSetText("Toque aqui para \n conversar com a tutora Atena.", <0, 0, 1.0>, 1.0);
    }

    touch_start(integer who) 
    {
       llSay(0,"A qualquer tempo digite mensagens no espaço de chat que está barra inferior. A tutora Atena está preparada para responder perguntar diretas sobre o assunto do laboratório."); 
        avatar = llDetectedKey(0);
        avatarName = llDetectedName(0);
        state chatting;
        llResetScript();
    }
}

state chatting
{
    state_entry()
    {
        llSetText("A Atena está conversando com " + avatarName, <0.0, 0.0, 0.0>, 1.0);
        listenChannel = llListen(77, "",  llDetectedKey(0), "");
    }

    touch_start(integer who)
    {
        if (avatar == llDetectedKey(0))
            state default;
        else llInstantMessage(llDetectedKey(0), "Desculpe, ainda estou conversando com " + avatarName);
        llResetScript();
    }

    listen(integer channel, string name, key id, string message)
    {
        llSetText("Esperando por resposta ...", <1.0, 1.0, 0.0>, 1.0);

        // have we started a conversation yet?  ORIGINAL ==>> JSON
        if (conversationID == "")
            conversationRequest = llHTTPRequest(programoURL
                + llEscapeURL(message)
            + "&bot_id=1"+"format=json"
            , [HTTP_METHOD, "GET", HTTP_MIMETYPE, "plain/text;charset=utf-8"], "");
             
            
        else // use the convo_id we have
            conversationRequest = llHTTPRequest(programoURL
                + llEscapeURL(message)
            + "&convo_id=" + conversationID
            + "&bot_id=1"+"format=json"
            , [HTTP_METHOD, "GET", HTTP_MIMETYPE, "plain/text;charset=utf-8"], "");


        // did we quit chatting?
        if (message == "quit" || message == "bye")
        {
            state default;
        }
    }
    
      
              
   http_response(key request_id, integer status, list metadata, string body)
    {
          if (request_id == conversationRequest){
            if (status != 200)
            {
                llSetText("Erro! Tente digitar algo novamente!", <1.0, 0.0, 0.0>, 1.0);
                llOwnerSay("HTTP Error " + (string)status + ": " + body);
            }
            else
            {
                llSetText("A Atena está conversando com " + avatarName + "\nconversa nro: " + conversationID, <0.0, 0.0, 0.0>, 1.0);
                string botReply = llDumpList2String(llParseStringKeepNulls(llGetSubString(body, llSubStringIndex(body, "\"botsay\":\"") + 10, -1), ["\\\""], []), "#@*$#");
                integer end = llSubStringIndex(botReply, "\""); // find real end of botsay element pointer
                if (end != 0) 
                {
                 botReply = llGetSubString(botReply, 0, end-1);//get the bot response
                  llStringTrim(botReply, STRING_TRIM); // remove all white space
                  botReply = llDumpList2String(llParseStringKeepNulls(botReply, ["#@*$#"], []), "\""); // replace tag with double quote
                  llInstantMessage(avatar, botReply);
                  }
                else botReply = ""; // response is empty
            }
        }
          
          
    }     
        }

**Comment by Dave-Morton** [comment] 2017-09-04 20:59
It sounds like there's something that's encoded as ASCII, rather than UTF8. Most likely it's your LSL script. What program do you use to write/edit the LSL script in?

**Comment by Dave-Morton** [comment] 2017-09-30 05:15
@alianrkeasan have you made any progress with this?

**Comment by alianrkeasan** [comment] 2017-09-30 18:43
Dear Dave,

I ain't got much progress since that day,

I'm still receiving messages with errors in accents and tilde

Like
 Voc\u00ea quer trocar o assunto para m\u00eddias na educa\u00e7\u00e3o?
(Você quer trocar o assunto para mídias na educação?)

But the problem is not with opensim or the viewer (Firestorm or Singularity) cause I have another bot that works fine.

Dont know what to do anymore and I didn't want to trouble you guys with that anymore.

Thanks for asking.

**Comment by alianrkeasan** [comment] 2017-09-30 18:44
Just to be clear: by bot works fine on the web, the problem is with the API.

**Comment by Dave-Morton** [comment] 2017-10-12 19:57
If the LSL script is encoded in anything other than UTF-8 any text that it outputs will be in that same encoding. Most standard text editors (even notepad) have a way to save files in  UTF-8 so I would check there. If you need help with this, please let me know which text editor you use and I'll see if I can provide some assistance.

**Comment by Dave-Morton** [comment] 2018-02-10 18:28
It's been 4 months since this issue was last active. Closing it for now. If it's still a problem, please reopen it and provide more data so it can be addressed.

**Closed by Dave-Morton** 2018-02-10 18:28 UTC
