### ISSUE TITLE
dev branch find_aiml.php does not show results from aiml_userdefined table?

### ISSUE THREAD

**Issue by rwaters71** [Program-O/Program-O#280] opened 2017-05-31 02:57 UTC
As the title says, seems the dev branch version of find_aiml.php does not return any results from the aiml_userdefined table?

It seems to execute the SQL query, finds a result (the result is only in aiml_userdefined table, not aiml), but then never adds it to the conversation array. Seems in that case WinningCategory variable remains undefined.. (at least that's what happens from my limited understanding of the debug logs/code).

I seem to get these errors in the debug log:

```
-----------------------
31-05-2017 07:17:57.16189[2][4] - Elapsed time: 0.046 milliseconds
[find_aiml.php][find_userdefined_aiml][1003]
User defined rows found: '1' 
-----------------------
31-05-2017 07:17:57.16193[1][4] - Elapsed time: 0.042 milliseconds
[find_aiml.php][Called outside of function][1042]
PHP ERROR [Notice] -Undefined variable: WinningCategory in /chatbot/core/aiml/find_aiml.php on Line 1042 
-----------------------
31-05-2017 07:17:57.16204[1][4] - Elapsed time: 0.110 milliseconds
[find_aiml.php][Called outside of function][1051]
PHP ERROR [Notice] -Undefined variable: WinningCategory in /chatbot/core/aiml/find_aiml.php on Line 1051 
-----------------------
31-05-2017 07:17:57.16211[1][4] - Elapsed time: 0.061 milliseconds
[find_aiml.php][Called outside of function][1052]
PHP ERROR [Notice] -Undefined variable: WinningCategory in /chatbot/core/aiml/find_aiml.php on Line 1052 
-----------------------
31-05-2017 07:17:57.16216[1][4] - Elapsed time: 0.051 milliseconds
[find_aiml.php][Called outside of function][1053]
PHP ERROR [Notice] -Undefined variable: WinningCategory in /chatbot/core/aiml/find_aiml.php on Line 1053 
-----------------------
31-05-2017 07:17:57.1622[1][4] - Elapsed time: 0.048 milliseconds
[find_aiml.php][Called outside of function][1055]
PHP ERROR [Notice] -Undefined variable: WinningCategory in /chatbot/core/aiml/find_aiml.php on Line 1055 
-----------------------
31-05-2017 07:17:57.16225[1][4] - Elapsed time: 0.050 milliseconds
[find_aiml.php][Called outside of function][1059]
PHP ERROR [Notice] -Undefined variable: WinningCategory in /chatbot/core/aiml/find_aiml.php on Line 1059 
-----------------------
31-05-2017 07:17:57.1623[1][4] - Elapsed time: 0.048 milliseconds
[find_aiml.php][Called outside of function][1059]
PHP ERROR [Notice] -Undefined variable: WinningCategory in /chatbot/core/aiml/find_aiml.php on Line 1059 
-----------------------
```
.. and then further down, there is no response, it pushes '' to the arrays

Pushing '' to the front of the [that_raw] array 
Pushing '' to the front of the [that] array 
Pushing '' to the front of the [parsed_template] array 
Pushing '' to the front of the [template] array 

.. and nothing gets output:

```
-----------------------
31-05-2017 07:17:57.16433[2][4] - Elapsed time: 0.027 milliseconds
[display_conversation.php][get_json][137]
Outputting response as JSON 
-----------------------
31-05-2017 07:17:57.16436[1][4] - Elapsed time: 0.035 milliseconds
[display_conversation.php][Called outside of function][146]
PHP ERROR [Notice] -Undefined index: data in /chatbot/core/conversation/display_conversation.php on Line 146 
-----------------------
31-05-2017 07:17:57.16445[4][4] - Elapsed time: 0.091 milliseconds
[display_conversation.php][get_json][151]
Returning JSON string: {"convo_id":".....","usersay":"Who likes MadDoc?","botsay":"","data":null} 
-----------------------
```

**Comment by patrickschur** [comment] 2017-05-31 14:04
In the function `find_userdefined_aiml` the query is not formed correctly. We will have to rewrite this a little bit. 
I will look at it later this day. Thanks for your help.

**Comment by rwaters71** [comment] 2017-05-31 14:44
Thanks for the quick response Patrick :)

**Comment by patrickschur** [comment] 2017-05-31 23:01
@rwaters71 This should be fixed now. Thanks for reporting! Let us know if you have more issues.

**Comment by rwaters71** [comment] 2017-05-31 23:46
@patrickschur Thanks for the working on it!

However, the results seem way too broad now, seems like a random answer from half the table.  A simple search for "WHERE IS SOFIA" returns an answer for:
```
SELECT `id`, `bot_id`, `pattern`, `thatpattern` , `template` FROM `sg_chatbot`.`aiml_userdefined` WHERE
   bot_id = '1' AND (`user_id` = '....' OR `user_id` = '-1')  AND (
  `pattern` = '_' OR
  `pattern` = '*' OR
  `pattern` = 'WHERE IS SOFIA' OR 
  `pattern` like 'WHERE % SOFIA' OR
  `pattern` like '**WHERE %**' OR
(`pattern` LIKE '**% IS %**') OR (`pattern` LIKE '% IS SOFIA' ) OR (`pattern` LIKE 'WHERE %') OR (`pattern` LIKE '% SOFIA' ) OR (`pattern` LIKE 'WHERE IS %')      OR
  `pattern` = 'RANDOM PICKUP LINE'
   OR 
 thatpattern REGEXP 'MADDOC' OR `thatpattern` LIKE '**%*%**' OR `thatpattern` LIKE '%_%'
  )  ORDER BY `pattern` ASC, `thatpattern` ASC,`id` ASC
```
The answer is unrelated, I imagine it matched "WHERE %" or "% IS %" or something like that?

**Comment by patrickschur** [comment] 2017-06-01 00:07
The query is a little bit messy, but correct. That's how Program-O works. Please don't forget the operators "*" and "_". 

For example if you have a pattern like `* SOFIA` you have to look for `% SOFIA` otherwise you wouldn't find it. Program-O creates a like pattern based on all options there are possible. To find the best result.

Notice it looks worse than it is. Is the first pattern a match it will break out.
If you any idea to make this cleaner or faster or both let me know. :)

**Comment by rwaters71** [comment] 2017-06-01 00:09
For reference, I looked up the same question in the Master branch, and the query seems much simpler:
```
SELECT * FROM `sg_chatbot`.`aiml_userdefined` WHERE
    `bot_id` = '1' AND
    (`user_id` = '....' OR `user_id` = '-1') AND
    `pattern` = 'WHERE IS SOFIA' 
```

The problem with the new query (while it may be correct semantically) is probably with order of the results then?  It does not return a direct match, it returns an answer to something like "*" or "% IS %" instead?

**Comment by patrickschur** [comment] 2017-06-01 00:18
And exactly this behavior is wrong. That's the reason why I fixed it and you haven't got any result back. :) Lets say you have another pattern called `WHERE IS *` and you look for `pattern = 'WHERE IS SOFIA'` it wouldn't find it. 

I look at it, but remember that the operator "_" has a higher priority than a direct word match. So it can be possible that the first result is not a word match.

**Comment by rwaters71** [comment] 2017-06-01 00:19
You are right. But it returned a result for the pattern "WHO IS ZDRASTVYI" instead of "WHERE IS SOFIA" ?

**Comment by patrickschur** [comment] 2017-06-01 00:24
Where is the pattern "WHO IS ZDRASTVYI"? In the "aiml_userdefined" table or in "aiml"?

**Comment by rwaters71** [comment] 2017-06-01 00:26
it is in the "aiml_userdefined" table. It is the last result in the long DEV query, out of ~80 resulting rows.

**Comment by patrickschur** [comment] 2017-06-01 00:29
Please correct me if I'm wrong. So you have (more than) two patterns in "aiml_userdefined".
One pattern is "WHERE IS SOFIA" and another pattern is "WHO IS ZDRASTVYI" and whenever you type "WHERE IS SOFIA" you get the other result back, right?

**Comment by rwaters71** [comment] 2017-06-01 00:32
Yes. I have about 100 patterns in the "aiml_userdefined" table.
There are no wildcards in the patterns colum of that table.
Both "WHERE IS SOFIA" and "WHO IS ZDRASTVYI" are patterns in the aiml_userdefuned table.
The above query returns the wrong result, not the template matching "WHERE IS SOFIA", but the template matching "WHO IS ZDRASTVYI" instead.

My skype id is philip71 btw, it it makes it easier.

**Comment by patrickschur** [comment] 2017-06-01 00:40
I don't have Skype only Facebook :D
Can you check if both patterns in the "aiml_userdefined" table have the same user_id and your convo_id is equal to the user_id?

**Comment by rwaters71** [comment] 2017-06-01 00:44
All the patterns in the "aiml_userdefined" table have the same user_id, yes. The convo_id is the same as the user_id, yes.

**Comment by patrickschur** [comment] 2017-06-01 00:49
Give me some minutes... :)

**Comment by patrickschur** [comment] 2017-06-01 01:12
Ok I came up with an idea and it works, but I get an empty response back... This will definitely take more time than I thought. :(

**Comment by rwaters71** [comment] 2017-06-01 01:13
I understand, sorry about the additional work.

**Comment by patrickschur** [comment] 2017-06-01 01:16
No worries you are welcome. :)

**Comment by patrickschur** [comment] 2017-06-01 01:27
Ok I made it. The pull request is coming soon. :+1:

**Comment by rwaters71** [comment] 2017-06-01 02:53
Seems to be working! It returns the correct responses now.

There seems to be another small issue though. If there are no matches, it returns "No AIML category found.. default erresponse." instead of random pickup line.

**Comment by Dave-Morton** [comment] 2017-06-01 04:23
I'm glad that you two were able to work things out, but it caused me two minor problems: first, you overflowed my inbox with this dialog :P and second, I had some other rather major changes to the same file that were the result of finding and fixing some somewhat unrelated bugs while working on a commercial project, so I'm going to have to reconcile the changes you've made with the changes I'
ve made, and that's going to take some time to unravel. {sigh!}

Still, though, I'm glad it's working for you. :)

**Comment by rwaters71** [comment] 2017-06-01 10:10
oops

**Comment by patrickschur** [comment] 2017-06-01 13:09
Sorry for that @Dave-Morton.

@rwaters71 You have to define a RANDOM PICKUP LINE category just like that:
```xml
<category>
  <pattern>RANDOM PICKUP LINE</pattern>
  <template>Whatever you want...</template>
</category>
```

**Comment by rwaters71** [comment] 2017-06-01 13:16
@patrickschur I have the category in the aiml table. It is not being picked up (in the latest dev branch commit from last night)

**Comment by Dave-Morton** [comment] 2017-06-01 14:10
Actually, it's not as bad as all that right now. All of the changes I've been making have been on a private sub-branch I'm using for a client at this point, so I don't have all that much to untangle, but I think I'll hold off on making the new additions/modifications until this issue is fully resolved. In the meantime, @rwaters71 could you post a debug file here that shows the issue you're currently experiencing, so that we have a starting point for figuring out what's going on? Thanks.

**Comment by Dave-Morton** [comment] 2017-06-01 14:14
Oh, if you need help with that, please read the wiki page on [reporting issues](https://github.com/Program-O/Program-O/wiki/Reporting-Issues) for details.

**Comment by rwaters71** [comment] 2017-06-01 14:41
Hello Dave.

The issue, now (with the dev branch), is that it searches the aiml_userdefined table, and if there are potential matches, it ONLY returns those potential results from the aiml_userdefined table, in such a case no default/random responses from the aiml table are returned.

Here is the bug report (note the sql query, seems the program only ever looked at the aiml_userdefined table):

```
01-06-2017 10:30:01.4463[0][0] - Elapsed time: 1.851 milliseconds
[conversation_start.php][Called outside of function][57]
Conversation starting. Current system specs:
  Program O version:            2.6.5
  Server Software:              Apache
  PHP Version:                  5.6.15
  OS:                           Linux
  OS Version:                   #1 SMP Mon Feb 2 21:00:58 UTC 2015
  MySQL Version:                10.0.21-MariaDB-log
  Multi-byte functions enabled: true 
-----------------------
01-06-2017 10:30:01.44785[0][0] - Elapsed time: 1.549 milliseconds
[conversation_start.php][Called outside of function][124]
Debug level: 0
session ID = 3f2e2531201cfbf853f16f668132eaf2 
-----------------------
01-06-2017 10:30:01.45639[0][3] - Elapsed time: 8.544 milliseconds
[conversation_start.php][Called outside of function][223]
Default debug level = 0 
-----------------------
01-06-2017 10:30:01.45644[0][3] - Elapsed time: 0.044 milliseconds
[conversation_start.php][Called outside of function][225]
Current debug level = 3 
-----------------------
01-06-2017 10:30:01.45646[0][3] - Elapsed time: 0.024 milliseconds
[conversation_start.php][Called outside of function][239]
Say = HOW DO YOU SAY THANKS IN GERMAN: raw say = how do you say thanks in german? 
-----------------------
01-06-2017 10:30:01.45649[2][3] - Elapsed time: 0.029 milliseconds
[intialise_conversation.php][push_on_front_convoArr][221]
Pushing 'HOW DO YOU SAY THANKS IN GERMAN' to the front of the [user_say] array 
-----------------------
01-06-2017 10:30:01.45655[0][3] - Elapsed time: 0.066 milliseconds
[intialise_conversation.php][add_new_conversation_vars][183]
User RAW = how do you say thanks in german?, RAW say = how do you say thanks in german? 
-----------------------
01-06-2017 10:30:01.45658[2][3] - Elapsed time: 0.025 milliseconds
[intialise_conversation.php][push_on_front_convoArr][221]
Pushing 'how do you say thanks in german?' to the front of the [input] array 
-----------------------
01-06-2017 10:30:01.46342[2][3] - Elapsed time: 6.840 milliseconds
[parse_aiml_as_XML.php][implode_recursive][137]
Imploding an array into a string. (recursively, if necessary) 
-----------------------
01-06-2017 10:30:01.46359[3][3] - Elapsed time: 0.167 milliseconds
[find_aiml.php][find_aiml_matches][1128]
Core Match AIML sql: SELECT `id`, `bot_id`, `pattern`, `thatpattern` , `template` FROM `sg_chatbot`.`aiml_userdefined` WHERE
   bot_id = '1' AND (`user_id` = '3f2e2531201cfbf853f16f668132eaf2' OR `user_id` = '-1')  AND (
  `pattern` = '_' OR
  `pattern` = '*' OR
  `pattern` = 'HOW DO YOU SAY THANKS IN GERMAN' OR 
  `pattern` like 'HOW % GERMAN' OR
  `pattern` like 'HOW %' OR
(`pattern` LIKE '% DO %') OR (`pattern` LIKE '% DO YOU SAY THANKS IN GERMAN' ) OR (`pattern` LIKE '% YOU %') OR (`pattern` LIKE 'HOW %') OR (`pattern` LIKE '% YOU SAY THANKS IN GERMAN' ) OR (`pattern` LIKE '% SAY %') OR (`pattern` LIKE 'HOW DO %') OR (`pattern` LIKE '% SAY THANKS IN GERMAN' ) OR (`pattern` LIKE '% THANKS %') OR (`pattern` LIKE 'HOW DO YOU %') OR (`pattern` LIKE '% THANKS IN GERMAN' ) OR (`pattern` LIKE '% IN %') OR (`pattern` LIKE 'HOW DO YOU SAY %') OR (`pattern` LIKE '% IN GERMAN' ) OR (`pattern` LIKE 'HOW DO YOU SAY THANKS %') OR (`pattern` LIKE '% GERMAN' ) OR (`pattern` LIKE 'HOW DO YOU SAY THANKS IN %')      OR
  `pattern` = 'RANDOM PICKUP LINE'
   OR 
 thatpattern REGEXP 'EVERYTHING|GOING|EXTREMELY' OR `thatpattern` LIKE '%*%' OR `thatpattern` LIKE '%_%'
  )  ORDER BY `pattern` ASC, `thatpattern` ASC,`id` ASC; 
-----------------------
01-06-2017 10:30:01.46579[2][3] - Elapsed time: 2.202 milliseconds
[find_aiml.php][find_aiml_matches][1135]
FOUND: (16) potential AIML matches 
-----------------------
01-06-2017 10:30:01.46614[1][3] - Elapsed time: 0.348 milliseconds
[find_aiml.php][unset_all_bad_pattern_matches][196]
Current THAT = EVERYTHING IS GOING EXTREMELY WELL 
-----------------------
01-06-2017 10:30:01.46623[2][3] - Elapsed time: 0.093 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46638[2][3] - Elapsed time: 0.151 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46647[2][3] - Elapsed time: 0.088 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46656[2][3] - Elapsed time: 0.086 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46664[2][3] - Elapsed time: 0.085 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46672[2][3] - Elapsed time: 0.084 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46681[2][3] - Elapsed time: 0.083 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.4669[2][3] - Elapsed time: 0.092 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.467[2][3] - Elapsed time: 0.101 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46709[2][3] - Elapsed time: 0.086 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46717[2][3] - Elapsed time: 0.084 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46725[2][3] - Elapsed time: 0.082 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46733[2][3] - Elapsed time: 0.080 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46741[2][3] - Elapsed time: 0.081 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46749[2][3] - Elapsed time: 0.082 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46758[2][3] - Elapsed time: 0.082 milliseconds
[find_aiml.php][build_wildcard_RegEx][361]
building wildcards for 'pattern'. 
-----------------------
01-06-2017 10:30:01.46765[1][3] - Elapsed time: 0.077 milliseconds
[find_aiml.php][unset_all_bad_pattern_matches][331]
Error: FOUND NO AIML matches in DB 
-----------------------
01-06-2017 10:30:01.46794[1][3] - Elapsed time: 0.283 milliseconds
[find_aiml.php][score_matches][477]
Found an error trying to identify the chatbot. 
-----------------------
01-06-2017 10:30:01.46803[2][3] - Elapsed time: 0.094 milliseconds
[find_aiml.php][get_winning_category][837]
And the winner is... -1! 
-----------------------
01-06-2017 10:30:01.46837[2][3] - Elapsed time: 0.340 milliseconds
[find_aiml.php][get_highest_scoring_row][806]
Empty Response! 
-----------------------
01-06-2017 10:30:01.46845[3][3] - Elapsed time: 0.079 milliseconds
[parse_aiml.php][parse_matched_aiml][213]
Run the aiml parse in normal mode (normal or srai) 
-----------------------
01-06-2017 10:30:01.46848[2][3] - Elapsed time: 0.034 milliseconds
[parse_aiml.php][set_wildcards][293]
Setting Wildcards. Pattern = 'no results' 
-----------------------
01-06-2017 10:30:01.46853[2][3] - Elapsed time: 0.044 milliseconds
[parse_aiml.php][set_wildcards][311]
compairing patterns no results and no results 
-----------------------
01-06-2017 10:30:01.46857[2][3] - Elapsed time: 0.045 milliseconds
[parse_aiml_as_XML.php][parse_aiml_as_XML][22]
Parsing the AIML template as XML 
-----------------------
01-06-2017 10:30:01.46861[2][3] - Elapsed time: 0.037 milliseconds
[parse_aiml_as_XML.php][add_text_tags][93]
Adding some TEXT tags into the template, just because I can... 
-----------------------
01-06-2017 10:30:01.46883[2][3] - Elapsed time: 0.216 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][201]
Recursively parsing the AIML template. 
-----------------------
01-06-2017 10:30:01.46905[2][3] - Elapsed time: 0.223 milliseconds
[parse_aiml_as_XML.php][parseTemplateRecursive][201]
Recursively parsing the AIML template. 
-----------------------
01-06-2017 10:30:01.46914[2][3] - Elapsed time: 0.087 milliseconds
[parse_aiml_as_XML.php][parse_text_tag][281]
Parsing a TEXT tag. 
-----------------------
01-06-2017 10:30:01.46918[2][3] - Elapsed time: 0.048 milliseconds
[parse_aiml_as_XML.php][implode_recursive][137]
Imploding an array into a string. (recursively, if necessary) 
-----------------------
01-06-2017 10:30:01.46924[2][3] - Elapsed time: 0.057 milliseconds
[parse_aiml_as_XML.php][implode_recursive][137]
Imploding an array into a string. (recursively, if necessary) 
-----------------------
01-06-2017 10:30:01.46931[2][3] - Elapsed time: 0.064 milliseconds
[intialise_conversation.php][push_on_front_convoArr][221]
Pushing 'No AIML category found.. default erresponse.' to the front of the [that_raw] array 
-----------------------
01-06-2017 10:30:01.46942[2][3] - Elapsed time: 0.119 milliseconds
[intialise_conversation.php][push_on_front_convoArr][221]
Pushing 'No AIML category found.. default erresponse.' to the front of the [that] array 
-----------------------
01-06-2017 10:30:01.46962[2][3] - Elapsed time: 0.200 milliseconds
[intialise_conversation.php][push_on_front_convoArr][221]
Pushing 'No AIML category found.. default erresponse.' to the front of the [parsed_template] array 
-----------------------
01-06-2017 10:30:01.4697[2][3] - Elapsed time: 0.071 milliseconds
[intialise_conversation.php][push_on_front_convoArr][221]
Pushing 'No AIML category found.. default erresponse.' to the front of the [template] array 
-----------------------
01-06-2017 10:30:01.46977[2][3] - Elapsed time: 0.071 milliseconds
[intialise_conversation.php][log_conversation][394]
Saving the conversation to the DB. 
-----------------------
01-06-2017 10:30:01.4698[3][3] - Elapsed time: 0.036 milliseconds
[intialise_conversation.php][log_conversation][432]
Saving conservation SQL: INSERT INTO `sg_chatbot`.`conversation_log` (
      `id` ,
      `input` ,
      `response` ,
      `user_id` ,
      `convo_id` ,
      `bot_id` ,
      `timestamp`
    )
    VALUES (
      NULL ,
      :usersay,
      :botsay,
      :user_id,
      :convo_id,
      :bot_id,
      CURRENT_TIMESTAMP
    ) 
-----------------------
01-06-2017 10:30:01.47036[3][3] - Elapsed time: 0.562 milliseconds
[display_conversation.php][get_conversation_to_display][54]
get_conversation SQL: SELECT * FROM `sg_chatbot`.`conversation_log`
        WHERE
        `user_id` = '1'
        AND `bot_id` = '1'
        AND `convo_id` = '3f2e2531201cfbf853f16f668132eaf2'
        ORDER BY id DESC  LIMIT 1  
-----------------------
01-06-2017 10:30:01.47074[2][3] - Elapsed time: 0.374 milliseconds
[display_conversation.php][get_conversation_to_display][70]
Found '1' lines of conversation 
-----------------------
01-06-2017 10:30:01.47079[2][3] - Elapsed time: 0.054 milliseconds
[display_conversation.php][get_json][137]
Outputting response as JSON 
-----------------------
01-06-2017 10:30:01.47091[2][3] - Elapsed time: 0.120 milliseconds
[conversation_start.php][Called outside of function][265]
Closing Database 
-----------------------
01-06-2017 10:30:01.47094[2][3] - Elapsed time: 0.032 milliseconds
[PDO_functions.php][db_close][52]
This DB is now closed. You don't have to go home, but you can't stay here. 
-----------------------
01-06-2017 10:30:01.47106[0][3] - Elapsed time: 0.112 milliseconds
[conversation_start.php][Called outside of function][272]
Conversation Ending. Elapsed time: 26.565 milliseconds. 
-----------------------
Debug Level: 3
-----------------------
Debug Mode: 1
-----------------------
CONVERSATION ARRAY
-----------------------
Array
(
    [conversation] => Array
        (
            [user_name] => Philip
            [convo_id] => 3f2e2531201cfbf853f16f668132eaf2
            [bot_name] => Eva
            [bot_id] => 1
            [format] => json
            [unknown_user] => guest
            [user_id] => 1
            [totallines] => 1
            [conversation_lines] => 1
            [remember_up_to] => 10
            [debugemail] => ...
            [debug_level] => 3
            [debugmode] => 1
            [save_state] => database
            [default_aiml_pattern] => RANDOM PICKUP LINE
            [bot_parent_id] => 1
            [rawSay] => how do you say thanks in german?
            [data] => Array
                (
                    [aiml_id] => -1
                    [bot_id] => 1
                    [pattern] => no results
                    [thatpattern] => 
                    [topic] => 
                    [score] => 0
                    [track_score] => No Match Found!
                )

        )

    [aiml] => Array
        (
            [user_raw] => how do you say thanks in german?
            [lookingfor] => HOW DO YOU SAY THANKS IN GERMAN
            [pattern] => no results
            [thatpattern] => 
            [template] => No AIML category found.. default erresponse.
            [html_template] => 
            [topic] => 
            [score] => 0
            [aiml_id] => -1
            [stars] => Array
                (
                )

            [parsed_template] => No AIML category found.. default erresponse.
        )

    [topic] => Array
        (
            [1] => 
        )

    [that] => Array
        (
            [1] => Array
                (
                    [1] => DEFAULT ERRESPONSE
                    [2] => NO AIML CATEGORY FOUND
                )

        )

    [input] => Array
        (
            [1] => how do you say thanks in german?
        )

    [stack] => Array
        (
            [top] => 
            [last] => 
        )

    [client_properties] => Array
        (
            [ip_address] => 68.67.73.20
            [name] => Philip
        )

    [user_say] => Array
        (
            [1] => HOW DO YOU SAY THANKS IN GERMAN
        )

    [that_raw] => Array
        (
            [1] => Array
                (
                    [1] => 
                    [2] => default erresponse.
                    [3] => No AIML category found..
                )

        )

    [parsed_template] => Array
        (
            [1] => No AIML category found.. default erresponse.
        )

)

-----------------------
Total execution time: 26.565 Milliseconds. Goodbye.
```

**Comment by patrickschur** [comment] 2017-06-01 14:48
For me the RANDOM PICKUP LINE works great... 

Program-O will first look at the "aiml_userdefined" table for a match if there is no match it will also look at the "aiml" table. 

So you want that he also look at the other table, right? Although there is a match?

**Comment by rwaters71** [comment] 2017-06-01 14:56
Yes, it would be nice if it looks in both tables.

In my case... there are some "potential" matches in the aiml_userdefined table. However, at some point later, after the query, Program-O (correctly) finds no "proper" match, and returns that "default error response", instead of looking up the "RANDOM PICKUP LINE" from the aiml table.

**Comment by patrickschur** [comment] 2017-06-01 15:26
It seems the problem is somewhere else. I noticed the line 'Found an error trying to identify the chatbot.' in your debug file. But I can't figure out why this happens.

Can we get web access to your bot?

**Comment by rwaters71** [comment] 2017-06-01 15:36
@patrickschur I just emailed you with the web address and the debug folder info.

**Comment by Dave-Morton** [comment] 2017-06-01 15:54
lol what am I, chopped liver? 😛

**Comment by Dave-Morton** [comment] 2017-06-01 15:59
@patrickschur that error is generated around line 477, in the section that checks both the bot ID, and any parent ID (if used). This obviously shouldn't happen, so we should put in some debugging code to see what the values are for `$bot_id` and `$bot_parent_id`, either before, or during the tests.

**Comment by Dave-Morton** [comment] 2017-06-01 16:03
@rwaters71  please insert the following code into line ~463, just after this line:

> # 1.) Check for current bot, rather than parent

`runDebug(__FILE__, __FUNCTION__, __LINE__, "Checking for bot/parent ID's: Bot ID = :bot_id. Parent Id = $bot_parent_id.", 4);`

**Comment by patrickschur** [comment] 2017-06-01 16:10
@Dave-Morton You dont say! :unamused:

**Comment by Dave-Morton** [comment] 2017-06-01 16:25
@patrickschur are you not on FB today?

**Comment by patrickschur** [comment] 2017-06-01 16:27
@Dave-Morton I replied to you a few minutes ago :stuck_out_tongue:

**Comment by Dave-Morton** [comment] 2017-06-01 16:35
Sorry. Messenger is buried under a ton of other windows.

**Comment by Program-O** [comment] 2017-09-02 12:13
marked as resolved no update from op over 30days

**Closed by Program-O** 2017-09-02 12:13 UTC
