### ISSUE TITLE
condition li  think  set  cannot set the value

### ISSUE THREAD

**Issue by Sabirjan** [Program-O/Program-O#418] opened 2018-06-08 03:19 UTC
```
   <category> <pattern>YES</pattern>
	<template>
	<condition>
		<li name="step" value="3"><think><set name="step">4</set></think>TEST1</li>
		<li name="step" value="6"><think><set name="step">0</set></think></li>TEST2</condition>
		STEP=<get name="step"></get>
	</template>	
   </category>
```

run result:
then step==3 , TEST1 STEP=3
then step==6  ,TEST2 STEP=6

can not set the step  value.

**Comment by Dave-Morton** [comment] 2018-06-08 09:53
Try writing your AIML category like this:

```
<category> <pattern>YES</pattern>
	<template>
		<condition>
			<li name="step" value="3"><think><set name="step">4</set></think>TEST1</li>
			<li name="step" value="6"><think><set name="step">0</set></think>TEST2</li>
		</condition>
		STEP=<get name="step"></get>
	</template>	
   </category>
```
If that doesn't work, then I suggest the following as an alternative:

```
<category> <pattern>YES</pattern>
	<template>
		<condition name="step">
			<li value="3"><think><set name="step">4</set></think>TEST1</li>
			<li value="6"><think><set name="step">0</set></think>TEST2</li>
		</condition>
		STEP=<get name="step"></get>
	</template>	
   </category>
```
If correcting the typo, as in my first suggestion doesn't work, then using the more common variant of the `<condition>` tag will. There are some minor glitches in some of the functions that parse the `<condition>` tag that we've been working on that may not have been addressed in the version of Program O that you're using. Another potential fix for this would be to download the latest version (2.6.10) from the `DEV` branch.

**Comment by Dave-Morton** [comment] 2018-06-09 13:27
Issues like this are almost invariably due to poor AIML, rather than bugs in the script, but they're not hard to fix if you know how AIML works. 😄

**Comment by OverlanAI** [comment] 2018-06-09 13:53
Yep, i just wanted to add it to Test suite that we currently have in some way so it could work standalone.
Setting Undefined works in both versions vrs value=0 then set it.

**Comment by tringate** [comment] 2018-07-15 02:09
This conversation is very confusing to me.  The reported issue of the THINK tag not allowing the set of a value is not a bug in the current DEV version.  I have hundreds of far more complex CONDITION statements using both versions of the CONDITION statement used in this example.  Both work perfectly.

This category is not following the suggested form.  Both should always have a default <li></li> as the last list entry.  It can be nothing more than an empty list entry which essentially is a no-op.  It is only testing for two values of "STEP" which are 3 and 6.  Any other value of STEP will result in no change at all to the value of STEP when the input of "YES" is detected.
This appears to be a tiny part of some other AIML set of categories which of course need to set what STEP is being used for and what you expect it to do when the word YES is typed.

Posting a problem saying a single category is failing without having what is expected and what the values are at entry is nearly impossible to give guidance on.  This example actually has invalid AIML in it as the closing </li> is missing as Dave pointed out.  When this is category is loaded into program-o you get an error saying your AIML is invalid.

Using this type of condition and ignoring the default catch all list element of the condition list only ensures this is going to be a headache in any AIML set.  While program-o does a good job of trying to guess what your really meant AIML itself is only as good as whoever wrote it.

This category will always print the value of STEP upon exiting the category.  There is no mention to what the logic is and what you are trying to accomplish.  You will need to post the other AIML categories that establish what STEP is set to and provided why this category is responding to the "YES" word.  We will also need to know what version of program-o your failure is occurring on.  There have been many intense code changes to the condition tag.  All addressed in one form or another issues with parts of the condition tag failing.  Not until the present version of the DEV branch have all three forms of CONDITION worked correctly.

The current DEV release will always return "undefined" for any value that has NEVER been set, so if STEP has never been set it's value if tested by CONDITION or retrieved with a GET will be "undefined".  However this category is not looking for that value nor is it looking for any values other than "3" and "6".  I have no idea what you are expecting this category to do as it appears to be a single category out of a more complex set of categories doing something with STEP.

In program-o any value that is UNASSIGNED, meaning it has never been used and does not exist in the database will return the text value of "undefined" .  If you use a SET tag to assign a value to a variable, it will NOW EXIST and it will return whatever value you place in it.

If you set it to nothing (="") it will not return "undefined".  This is because it now exists and has a blank value.  It will not return "0" unless you set it to have a value of "0".

It is very bad programming practices to use a variable without first setting it's value. In AIML it is more than a bad practice, it is a sure way to have your AIML NOT work as expected.

**Comment by Dave-Morton** [comment] 2018-07-16 11:03
All very good points, @tringate . Thanks for that. 😄

**Comment by OverlanAI** [comment] 2018-07-19 01:02
Cant have it all but works :)

Tnx (Argent Hold you head Up, works for me)

**Comment by Program-O** [comment] 2018-08-02 01:33
@Sabirjan is this now resolved?

**Comment by tringate** [comment] 2018-08-02 21:06
It does not fail for me.  Without the actual AIML including how STEP is being set I can not comment on if your issue is solved or not.

The think tag is able to set a value inside a list, and in a condition list element.

**Comment by patrickschur** [comment] 2018-08-08 07:08
Looks like this issue is solved. If not please reopen.

**Closed by patrickschur** 2018-08-08 07:08 UTC
Labels: review
