### ISSUE TITLE
{"error":"Check the logs!","botsay":"Houston, we have a problem!"}

### ISSUE THREAD

**Issue by semantus** [Program-O/Program-O#358] opened 2018-02-08 18:07 UTC
Dear Support,

After using https://www.semanta.nl/semanta/program_o/gui/plain/receptioniste.php succesfully i receive the message {"error":"Check the logs!","botsay":"Houston, we have a problem!"} and have no clue where to look for a solution

Kind regards

ed Kool
Lingvistica
[8e5db79174c10aa14768912b01640f68.txt](https://github.com/Program-O/Program-O/files/1708252/8e5db79174c10aa14768912b01640f68.txt)

**Comment by Dave-Morton** [comment] 2018-02-10 06:40
@semantus I looked at that debug file, but it contained no reference to the PHP error that triggered that error message. I also tried to follow the link you provided to chat with the bot myself, so that I could do some checking on my own, but it's password protected, so I'm not able to proceed there. The error message you're receiving is caused by something going wrong in the file chatbot/core/aiml/find_aiml.php within the function `unset_all_bad_pattern_matches()', probably on  line 111 (depending on which version you're running), which performs a RegEx match looking for wildcards in the patterns of potential AIML categories to match. I really can't tell beyond that what's going on without access to more information.

**Comment by Dave-Morton** [comment] 2018-03-04 07:10
I found the problem here, and it's been addressed in the upcoming bug fix. There was no log entry because the script involved had an ancient call to die() that was being triggered. That's been removed, and the underlying cause (the problem that triggered that old die() call) __seems__ to have been addressed. At least it stopped showing up during testing and hasn't come back since. :smile:

**Comment by Dave-Morton** [comment] 2018-05-08 13:29
This has been kicking around with no new info for a while now, so I'm closing the issue. If new information becomes available, please either reopen this issue, or create a new one. Thanks.

**Closed by Dave-Morton** 2018-05-08 13:29 UTC
Labels: review
