### ISSUE TITLE
Is <sraix> supported in program O

### ISSUE THREAD

**Issue by alokraj68** [Program-O/Program-O#347] opened 2017-12-12 07:11 UTC
Hi,
Recently we were making a set of bots in such a way that a parent AIML bot will route the request based on the tag to child bots.
But we could not achieve it in program O.
We where surprised to see <sraix> tag is not available in program O
Can someone guide us on this process?
Is SRAIX tag renamed to something else in program o?

**Comment by Dave-Morton** [comment] 2017-12-13 05:24
The `<sraix>` tag is a feature of AIML 2.0, which Program O does not yet support. This is being addressed in Program O version 3, but that isn't yet ready to be released, even as a beta version. I wish I had better news for you, but I do not. Sorry.

**Comment by Dave-Morton** [comment] 2018-02-10 18:17
With no further input for this issue after 2 months, it's time to close it.

**Closed by Dave-Morton** 2018-02-10 18:17 UTC

**Comment by alokraj68** [comment] 2018-02-10 19:10
Hi,
how is the parent/child relationship possible?

When can we expect Program O 3.0

**Comment by Dave-Morton** [comment] 2018-02-11 18:36
Let's say you have a chatbot (bot_id of 1) with a full ALICE AIML set. When you create a new chatbot (bot_id of 2) you can set that bot up in the admin page to be a child of the first chatbot so that it's a child of the first. Then when a user chats with the "child" bot, if there is no AIML in the child bot to cover the user's input, Program will look for a suitable AIML category in the parent bot's database, and will return the response from that AIML category. this way you save a lot of resources by not having to add a full AIML set for each chatbot. The admin page for your Program O install has some fairly comprehensive help sections (though some are currently not being displayed - going to have to look into why that is). Just look for a blue "help" cube. Clicking on it will toggle any available help for that panel.

**Comment by alokraj68** [comment] 2018-02-11 18:46
Thanks a lot for the response. How about having multiple child's for same
parent. Will that be possible?

**Comment by Dave-Morton** [comment] 2018-02-11 21:25
Certainly, that's possible. The only thing you cannot do is "stack" parents. For example, if bot A is the parent of bot B, you won't gain anything useful if you have bot B as the parent of a 3rd bot, C. Bot inheritance is only one level, and that's by design.

**Comment by alokraj68** [comment] 2018-02-17 16:38
@Dave-Morton That's cool. We are looking forward to <sraix> tag in program O 3.0
