### ISSUE TITLE
The _ wildcard does not have precedence. The matching algorithm is wrong!

### ISSUE THREAD

**Issue by salvadorjesus** [Program-O/Program-O#79] opened 2015-04-18 19:10 UTC
According to the AIML definition (just consulted 1.0.1, section 8.4 and others http://www.alicebot.org/TR/2001/WD-aiml/#section-aiml-wildcards), the _ wildcard must be attempted to match before anything else.

Program O does not work like that, and thus works against the specification.

Consider this example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<aiml version="1.0">
<category>
<pattern>WHAT IS A HUMAN </pattern>
  <template>R1</template>
  </category>
<category>
<pattern>WHAT IS * </pattern> 
  <template>R2</template>
  </category>
<category>
  <pattern>_ IS * </pattern>
  <template>R3</template>
</category>
</aiml>
```
With the input: What is a human
The expected results is R3. But programo returns R1.

You can try Pandora to check the correct result of R3. I haven't try this particular example with program AB, but I'm pretty sure the result would be R3, because I have observed a similar behavior with Alice.
I have experience this issue with Program O 2.3.1, in an installation of 2013, and 2.4.7, in a recent installation, in WAMP and LAMP, so I guess the algorithm has always behaved like that.

**Comment by salvadorjesus** [comment] 2015-04-18 19:23
On a side, less formal note, I am using Program O as a backend for this game:
http://gamejolt.com/games/adventure/turing-adventure/59029/

I like Program O and I like you people, but I'm having a really hard time trying to trick Program O to work as expected. This is the main issue I'm having. There are other issues, and there are some design decisions taken to build Program O that I do not _enjoy_. I expect to report those here or in the forum.

For the moment I am not naming Program O in the game nor in other related media, but this is because of the issues I have. If we can solve them, I would gladly tell everybody!

I can see that Pandora is pushing its business forward, Cortana is about to appear in all Windows 10 machines (W10 will be a free upgrade)... This is our time, folks!

**Comment by stevebasher** [comment] 2015-12-23 23:46
Did you figure out a solution for this in the end?

**Comment by xtcian** [comment] 2015-12-24 10:04
Uhm... I am sorry to say but that formula is working as expected? I am
using a persion of program-o thats about 2y old tho... and tweaked and
modified a lot.. cant remember if that worked as intended originally or
not. Just to clear a very very common mistake 99% of people make with
wildcards....

1) a perfect match takes preference on all.. and then its the latest
perfect match in database...

2) if no perfect match is found.. THEN the _ wildcard is next..

3) if no _ found.. THEN it goes to *

4) if more than 1 wildcard.. it picks the one with most words correctly
matched in place...

5) if more than 1 match there..
Example: "how are you today" vs "how * *" and "how  *"
Then the one withe most wildcards win vs only 1 wildcard.

So if user input "how are you today" then order of matching is suppose to
be in this order:

A) how are you today
B) _ are _
C) _ are *
D) _
E) how are * *
F) how * *
G) how *
H) *

Thats the way its originally intended as far as I know.. and following that
standard there is nothing that cannot be achieved.. you can control
everything.
However...
Depending on what version of php you run on server... that gets errored and
bugged... due to the code matching the sql.

I dont know if its been fixed in latest commit... I found php 5.2 worked
the best for me tho...

I hope this helped.

**Comment by stevebasher** [comment] 2015-12-24 13:41
Thanks for the comprehensive reply, really appreciate it! The problem I'm having, however, is that Program-O simply isn't matching any pattern that starts with either wildcard. 

For example, having the category:
<category>
      <pattern>_ Steve</pattern>
      <template><srai><star /></srai></template>
</category>

Isn't matched at all when inputting something like 'Hello Steve' or 'My name is Steve', when, unless i'm completely mistaken, it should be?

I have Program-O version 2.4.7 and I'm hosting it on GoDaddy so I assume my PHP version is up to date to. Any idea on what's going wrong? I'd really appreciate the help, thanks. 

Steve

**Comment by salvadorjesus** [comment] 2015-12-24 18:17
Dear Steve Basher, thanks for the interest,
Dear Xtician, thanks for your wide reply,

Please apologize me for disagreeing. But I believe that what I said is correct; The _ wildcard has preference always, even to a perfect match.

Please consider the following:

a) The specification:

http://www.alicebot.org/TR/2001/WD-aiml/#section-pattern-expression-matching-behavior

For me it’s quite clear. Remember that the matching through the graph is word by word, not against the whole category.

b) It’s work as I describe in other implementations. If you use my example on Pandora (a business backed by dr. Wallace, I believe) it’s working as I describe. I checked it before posting the original bug report.

Further, if you try program AB, the *reference implementation*, it works as I describe. I just checked it before writing you.

With Program O, it works differently.

--
Arguments aside, it makes sense. The _ wildcard is mainly used to make substitutions, like to correct commons misspelling, and then launch the query again. For example, Alice substitutes colour for color. Properly used (and properly working), it can save a *lot of work* when writing aiml files.

I know it can potentially leave some categories (the perfect match) unreachable if you write categories with _, but then again, that is the point of the _ wildcard, to have precedence. Those unreachable categories would be bad designed.

As I said, it saves you a lot of work, and, although no example comes at this moment to my mind (sorry), I would say that there are certain things you cannot achieve without a _ with aiml with precedence. Not even Alice works the same on Pandora, and Program O, and because of this. It’s hard to see, because you get a reply, but it’s smarter in Pandora. I wish I saved some examples, sorry again.

--
Now, with Program O, I examined the code months and, if I didn’t misunderstand (I cannot really write php), this is done on purpose, so it’s not a bug, it’s a feature. One that, because of the reasons I gave above -and if I am not mistaken-, should be reconsidered.

I’ve been looking into the code before replying trying to find that part of the code but I couldn’t. It’s been two hours with this reply and I cannot spare more time in a day like today ;).

--
Steve, replying to your question, I just moved to Pandora. I might want to come back and fix it in the coming months, maybe using some professional help, but I’m not sure when or “even if”.

Thank you very much for your time and interest!

Happy holidays to all!

P.S.: Looking for an example by dr. Wallace I read time ago, I stumbled into this, which is not what I wanted, but may be helpful: http://pandorabots.com/static/html/sharedglossary.html#term-wild-cards

**Closed** 2016-02-01 09:30 UTC
