### ISSUE TITLE
aiml not downloading

### ISSUE THREAD

**Issue by student189** [Program-O/Program-O#274] opened 2017-05-09 19:01 UTC
all my aiml categories work fine but I am not able to download the aiml files

**Comment by patrickschur** [comment] 2017-05-09 20:23
Can you give us further information about that? We need to reproduce that behaviour otherwise we can't help you. Because for me the download works just fine.

Please let us know which operating system and PHP version your using.
Also make sure that your PHP was compiled with the `--enable-zip` option, which should be default by the way. 

Did you get any error message back? If yes this can help us a lot too, if not have a look at the `logs` folder. That is the place where the debugging files are saved.

**Comment by GaneshKandu** [comment] 2017-05-11 12:16
use ```&amp;```  on the place of ```&```

**Comment by GaneshKandu** [comment] 2017-05-11 12:18
use ```&amp;```  at the place of ``&```

**Comment by Program-O** [comment] 2017-06-27 01:11
closed as resolved by @student189

**Closed by Program-O** 2017-06-27 01:11 UTC
